# Generated by Django 2.0.7 on 2018-07-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('population', models.IntegerField(verbose_name='人口数量')),
                ('author', models.CharField(default='', max_length=100, verbose_name='负责人')),
                ('fans_num', models.IntegerField(default=0, verbose_name='加粉数量')),
                ('created_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
            ],
        ),
    ]
