# Generated by Django 2.0.7 on 2018-07-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180710_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_id', models.BigIntegerField(max_length=20)),
                ('province_name', models.CharField(max_length=64)),
                ('city_id', models.BigIntegerField(max_length=20)),
                ('city_name', models.CharField(max_length=64)),
                ('county_id', models.BigIntegerField(max_length=20)),
                ('county_name', models.CharField(max_length=64)),
                ('town_id', models.BigIntegerField(max_length=20)),
                ('town_name', models.CharField(max_length=64)),
                ('village_id', models.BigIntegerField(max_length=20, unique=True)),
                ('village_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='user',
        ),
    ]
