# Generated by Django 2.0.7 on 2018-07-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180711_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='county_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='province_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='town_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='village_name',
            field=models.CharField(max_length=200),
        ),
    ]
