# Generated by Django 2.0.7 on 2018-07-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180711_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_id', models.IntegerField(verbose_name='省份id')),
                ('city_id', models.BigIntegerField(unique=True, verbose_name='市id')),
                ('city_name', models.CharField(max_length=64, verbose_name='市名称')),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(verbose_name='市id')),
                ('county_id', models.IntegerField(verbose_name='县id')),
                ('county_name', models.CharField(max_length=64, verbose_name='县名称')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_id', models.IntegerField(unique=True, verbose_name='省份id')),
                ('province_name', models.CharField(max_length=32, verbose_name='省份名称')),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
