# Generated by Django 2.0.7 on 2018-07-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180711_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='city_id',
            field=models.BigIntegerField(verbose_name='市id'),
        ),
        migrations.AlterField(
            model_name='county',
            name='county_id',
            field=models.BigIntegerField(verbose_name='县id'),
        ),
        migrations.AlterField(
            model_name='county',
            name='county_name',
            field=models.BigIntegerField(max_length=64, verbose_name='县名称'),
        ),
    ]
