# Generated by Django 2.0.7 on 2018-07-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180711_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='county_name',
            field=models.CharField(max_length=64, verbose_name='县名称'),
        ),
    ]
