# Generated by Django 2.0.7 on 2018-07-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180712_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areainfo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='地区名称'),
        ),
    ]
