# Generated by Django 2.0.7 on 2018-07-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180712_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechatId', models.CharField(max_length=100, verbose_name='微信ID')),
                ('QRCode', models.ImageField(upload_to='upload/', verbose_name='微信二维码')),
                ('state', models.CharField(choices=[(0, '封号'), (1, '正常')], max_length=2)),
            ],
            options={
                'verbose_name': '微信账户',
                'verbose_name_plural': '微信账户',
            },
        ),
    ]
