# Generated by Django 2.0.7 on 2018-07-12 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_wechatinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='area_info',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='app.AreaInfo', verbose_name='地区'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='dialog_num',
            field=models.IntegerField(default=0, verbose_name='对话数量'),
        ),
        migrations.AddField(
            model_name='article',
            name='group_add_num',
            field=models.IntegerField(default=0, verbose_name='加群数量'),
        ),
        migrations.AddField(
            model_name='article',
            name='send_invited_num',
            field=models.IntegerField(default=0, verbose_name='发出的好友邀请数量'),
        ),
        migrations.AddField(
            model_name='article',
            name='send_zone_for_friend_num',
            field=models.IntegerField(default=0, verbose_name='帮忙推送朋友圈数量'),
        ),
        migrations.AddField(
            model_name='article',
            name='send_zone_num',
            field=models.IntegerField(default=0, verbose_name='推送朋友圈数量'),
        ),
        migrations.AlterField(
            model_name='wechatinfo',
            name='state',
            field=models.CharField(choices=[(0, '封号'), (1, '正常')], default=1, max_length=2),
        ),
    ]
