# Generated by Django 2.0.7 on 2018-07-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180713_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='wechat_id',
            field=models.CharField(default='empty', max_length=64, verbose_name='微信ID'),
            preserve_default=False,
        ),
    ]
