# Generated by Django 2.0.7 on 2018-07-14 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20180714_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
